# Building client
FROM node:16-alpine as build-service

ARG HARVEST_API_URL
ARG OAUTH_APP_ID
ENV HARVEST_API_URL=${HARVEST_API_URL}
ENV OAUTH_APP_ID=${OAUTH_APP_ID}

WORKDIR /app

COPY ./package.json .
RUN npm i

COPY . .
RUN npm run production

# Starting harvest-app
FROM nginx:latest as harvest-app
COPY --from=build-service /app/out /var/www/html
ADD /config/nginx/nginx.conf /etc/nginx/nginx.conf
