version: '3'
services:
  api:
    env_file:
      - ../.env
    volumes:
      - ../api:/app
      - /app/node_modules
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - harvest.dashboard
networks:
  harvest.dashboard:
    name: harvest.dashboard
    external: true
