version: '3'
services:
  client:
    build:
      context: ../.
      dockerfile: docker/client/Dockerfile.dev
    image: harvest-client-dev
    volumes:
      - ../client:/app
      - /app/node_modules
    ports:
      - '3000:3000'
