# Building client
ARG HARVEST_API_URL
ARG OAUTH_APP_ID

FROM node:14-alpine as build-service

ARG HARVEST_API_URL
ARG OAUTH_APP_ID
ENV HARVEST_API_URL=${HARVEST_API_URL}
ENV OAUTH_APP_ID=${OAUTH_APP_ID}

WORKDIR /app

COPY ./client/package.json .
RUN npm i

COPY ./client .
RUN npm run build

# Starting harvest-app
FROM nginx:latest as harvest-app
COPY --from=build-service /app/dist /var/www/html
ADD /config/nginx/nginx.conf /etc/nginx/nginx.conf
