# This workflow automatically bumps the repos patch version
# If you include #major, #minor or #patch in your commit-message, the workflow
# will update the version based on this input

name: Test Action
on:
  push:
jobs:
  jest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: "Run Jest Tests"
      - run: npm ci --legacy-peer-deps
      - run: npm test
